### ISSUE TITLE
failed to run , cant install simpleaudio

### ISSUE THREAD

**Issue by prinsharma1999** [LeviBorodenko/spectrographic#2]
i try to run but everythng got f**ked at simpleaudio  . i tried pip install simpleaudio but failed any solution do you have i am runing kali linux 2019.4

**Comment by LeviBorodenko** [comment]
[According to the simpleaudio docs](https://simpleaudio.readthedocs.io/en/latest/installation.html#installation-ref) for Debian variants (including Raspbian), you should run  `sudo apt-get install -y python3-dev libasound2-dev` before installing simpleaudio via pip.

**Comment by prinsharma1999** [comment]
thanks bro , it just worked fine but i think i have others problems
